#version 450

layout (local_size_x = 128) in;

#include "../particle_util.inc.comp"

#include "../ssbos.inc.comp"

layout (std430, binding = 5) buffer squared_residual_buffer {
    float squared_residuals[];
};

void main() {
    uint id = gl_GlobalInvocationID.x;
    if (id >= N) {
        return;
    }
    Particle p = particles[id];
    p.p.xyz = mat3(p.precond) * p.residual.xyz;
    particles[id].p.xyz = p.p.xyz;
    squared_residuals[id] = dot(p.residual.xyz, p.p.xyz);
}
