#version 450

layout (local_size_x = 128) in;

layout (std430, binding = 3) buffer cell_counter_buffer {
    int cell_counter[];
};

layout (std430, binding = 7) buffer boundary_cell_counter_buffer {
    int boundary_cell_counter[];
};

void main() {
    uint id = gl_GlobalInvocationID.x;
    if (id >= CELL_COUNT) {
        return;
    }
    cell_counter[id] = 0;
    boundary_cell_counter[id] = 0;
}
