set(GLEW_SEARCH_PATHS ${DEPENDENCIES_PATH})

find_path(GLEW_INCLUDE_PATH
    NAMES GL/glew.h
    PATHS ${GLEW_SEARCH_PATHS}
    PATH_SUFFIXES include)

find_library(GLEW_LIBRARIES
    NAMES libGLEW.a glew glew32s.lib glew32sd.lib
    PATHS ${GLEW_SEARCH_PATHS}
    PATH_SUFFIXES lib)

set(GLEW_FOUND "NO")
if (GLEW_INCLUDE_PATH AND GLEW_LIBRARIES)
    set(GLEW_FOUND "YES")
    message("EXTERNAL LIBRARY 'GLEW' FOUND")
else ()
    message("ERROR: EXTERNAL LIBRARY 'GLEW' NOT FOUND")
endif (GLEW_INCLUDE_PATH AND GLEW_LIBRARIES)