set(ASSIMP_SEARCH_PATHS ${DEPENDENCIES_PATH})

find_path(ASSIMP_INCLUDE_PATH
    NAMES assimp/mesh.h
    PATHS ${ASSIMP_SEARCH_PATHS}
    PATH_SUFFIXES include)

find_library(ASSIMP_LIBRARIES
    NAMES assimp libassimp.so
    PATHS ${ASSIMP_SEARCH_PATHS}
    PATH_SUFFIXES lib)

set(ASSIMP_FOUND FALSE)
if (ASSIMP_INCLUDE_PATH AND ASSIMP_LIBRARIES)
    set(ASSIMP_FOUND TRUE)
    message("EXTERNAL LIBRARY 'ASSIMP' FOUND")
else (ASSIMP_INCLUDE_PATH AND ASSIMP_LIBRARIES)
    message("ERROR: EXTERNAL LIBRARY 'ASSIMP' NOT FOUND")
endif (ASSIMP_INCLUDE_PATH AND ASSIMP_LIBRARIES)
