set(IMGUI_SEARCH_PATHS ${DEPENDENCIES_PATH})

find_path(IMGUI_INCLUDE_PATH
    NAMES IMGUI/imgui.h
    PATHS ${IMGUI_SEARCH_PATHS}
    PATH_SUFFIXES include)

find_library(IMGUI_LIBRARIES
    NAMES imgui.a imgui.lib
    PATHS ${IMGUI_SEARCH_PATHS}
    PATH_SUFFIXES lib)

set(IMGUI_FOUND FALSE)
if (IMGUI_INCLUDE_PATH AND IMGUI_LIBRARIES)
    set(IMGUI_FOUND TRUE)
    message("EXTERNAL LIBRARY 'IMGUI' FOUND")
else (IMGUI_INCLUDE_PATH AND IMGUI_LIBRARIES)
    message("ERROR: EXTERNAL LIBRARY 'IMGUI' NOT FOUND")
endif (IMGUI_INCLUDE_PATH AND IMGUI_LIBRARIES)
