set(GLFW3_SEARCH_PATHS ${DEPENDENCIES_PATH})

find_path(GLFW3_INCLUDE_PATH
    NAMES GLFW/glfw3.h
    PATHS ${GLFW3_SEARCH_PATHS}
    PATH_SUFFIXES include)
find_library(GLFW3_LIBRARIES
    NAMES glfw3
    PATHS ${GLFW3_SEARCH_PATHS}
    PATH_SUFFIXES lib
)

set(GLFW3_FOUND "NO")
if (GLFW3_INCLUDE_PATH AND GLFW3_LIBRARIES)
    set(GLFW3_FOUND "YES")
    message("EXTERNAL LIBRARY 'GLFW3' FOUND")
else ()
    message("ERROR: EXTERNAL LIBRARY 'GLFW3' NOT FOUND")
endif (GLFW3_INCLUDE_PATH AND GLFW3_LIBRARIES)
