set(GLM_SEARCH_PATHS ${DEPENDENCIES_PATH})

find_path(GLM_INCLUDE_PATH
    NAMES glm/glm.hpp
    PATHS ${GLM_SEARCH_PATHS}
    PATH_SUFFIXES include)

set(GLM_FOUND "NO")
if (GLM_INCLUDE_PATH)
    set(GLM_FOUND "YES")
    message("EXTERNAL LIBRARY 'GLM' FOUND")
else ()
    message("ERROR: EXTERNAL LIBRARY 'GLM' NOT FOUND")
endif (GLM_INCLUDE_PATH)
